# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_endpoint', '0002_kerasmodelweights'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerasmodelweights',
            name='weight_name',
            field=models.CharField(default='init', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kerasmodelweights',
            name='weight_file',
            field=models.FileField(upload_to='weights/'),
        ),
    ]
