# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keras_endpoint', '0003_auto_20170708_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kerasmodelweights',
            name='weight_file',
            field=models.FileField(upload_to=b''),
        ),
    ]
