# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keras_endpoint', '0006_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictTask',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('callback_url', models.URLField(null=True)),
                ('input', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskSuccessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTask',
            fields=[
                ('name', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('callback_url', models.URLField(null=True)),
                ('config', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keras_endpoint.Dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='kerasmodelweights',
            name='weight_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='traintask',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keras_endpoint.KerasModelWeights'),
        ),
        migrations.AddField(
            model_name='tasksuccessor',
            name='next_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_task', to='keras_endpoint.TrainTask'),
        ),
        migrations.AddField(
            model_name='tasksuccessor',
            name='previous_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_task', to='keras_endpoint.TrainTask'),
        ),
        migrations.AddField(
            model_name='predicttask',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keras_endpoint.KerasModelWeights'),
        ),
    ]
