# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keras_endpoint', '0007_auto_20170712_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('of_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='keras_endpoint.PredictTask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('result', models.FileField(upload_to=b'')),
                ('of_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='keras_endpoint.TrainTask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
