# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keras_endpoint', '0008_predictresult_trainresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictresult',
            name='of_task',
        ),
        migrations.RemoveField(
            model_name='trainresult',
            name='of_task',
        ),
        migrations.DeleteModel(
            name='PredictResult',
        ),
        migrations.DeleteModel(
            name='TrainResult',
        ),
    ]
