# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainresult',
            name='history',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
